# Generated by Django 3.2.4 on 2021-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
